networks:
  default:
    driver: bridge

volumes:
  postgres:

services:
  vulpix-back-end:
    build: .
    networks:
      - default
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file: .env
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
