networks:
  default:
    driver: bridge

volumes:
  postgres-data:

services:
  vulpix-back-end:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    ports:
      - 8080:8080
    depends_on:
      prisma-migrate:
        condition: service_completed_successfully

  prisma-migrate:
    image: node:alpine
    env_file: .env
    networks:
      - default
    working_dir: /app
    volumes:
      - ./prisma:/app/prisma
    command: sh -c "npx prisma migrate dev --skip-generate"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    env_file: .env
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 10s
