networks:
  default:
    driver: bridge

volumes:
  postgres-data:

services:
  vulpix-back-end:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - 3000:3000

  postgres:
    image: postgres
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env
