networks:
  default:
    driver: bridge

volumes:
  postgres:

services:
  api:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - default
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: ../.env
    networks:
      - default
