networks:
  default:
    driver: bridge

volumes:
  postgres-data:

services:
  vulpix-back-end:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/vulpix-back-end:cached
    networks:
      - default
    command: sleep infinity

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default
    env_file: ../.env
