networks:
  default:
    driver: bridge

volumes:
  postgres:

services:
  vulpix-back-end:
    image: mcr.microsoft.com/vscode/devcontainers/javascript-node
    volumes:
      - ..:/workspaces/vulpix-back-end:cached
    networks:
      - default
    command: sleep infinity
    depends_on:
      - postgres

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default
    env_file: ../.env
