name: Unit Testing

on:
  push:
    branches:
      - main

jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma modules
        run: pnpx prisma generate

      - name: Run unit tests
        run: pnpm test
